name: Terraform Format Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  terraform-fmt:
    name: Terraform Fmt Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
